admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: {address: 127.0.0.1, port_value: 9901, protocol: TCP}
static_resources:
  clusters:
  - connect_timeout: 0.25s
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: {address: localhost, port_value: 7080}
    name: service
    type: LOGICAL_DNS
  - connect_timeout: 0.25s
    http2_protocol_options: {}
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: rate_limit_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: {address: localhost, port_value: 8080}
    name: rate_limit_service
    type: LOGICAL_DNS
  listeners:
  - address:
      socket_address: {address: 0.0.0.0, port_value: 10000, protocol: TCP}
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          http_filters:
          - config:
              domain: service
              failure_mode_deny: false
              rate_limit_service:
                grpc_service:
                  envoy_grpc: {cluster_name: rate_limit_cluster}
                  timeout: 0.25s
              stage: 0
            name: envoy.rate_limit
          - {name: envoy.router}
          route_config:
            name: local_route
            virtual_hosts:
            - domains: ['*']
              name: local_service
              routes:
              - match: {prefix: /}
                route:
                  cluster: service
                  rate_limits:
                  - actions:
                    - generic_key: {descriptor_value: default}
                    stage: 0
                  retry_policy: {num_retries: 3, retry_on: '5xx,reset'}
          stat_prefix: ingress_http
    name: listener_0
